# Generated by Django 5.2.4 on 2025-07-21 14:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Ex: S001, S002...', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cin', models.CharField(help_text="Carte d'identité nationale", max_length=20, unique=True)),
                ('fonction', models.CharField(help_text='Ex: Technicien, Comptable...', max_length=100)),
                ('date_embauche', models.DateField()),
                ('salaire_base', models.DecimalField(decimal_places=2, help_text='Salaire mensuel de base en DH', max_digits=10)),
                ('situation_familiale', models.CharField(choices=[('C', 'Célibataire'), ('M', 'Marié(e)'), ('D', 'Divorcé(e)'), ('V', 'Veuf/Veuve')], default='C', max_length=1)),
                ('nombre_enfants', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('banque', models.CharField(blank=True, max_length=100)),
                ('numero_compte', models.CharField(blank=True, max_length=30)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='ParametrePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Ex: Barème IR 2025, Taux CNSS...', max_length=100)),
                ('code', models.CharField(help_text='Ex: IR_2025, CNSS_2025', max_length=20, unique=True)),
                ('valeur_numerique', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valeur_pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='En %', max_digits=5, null=True)),
                ('valeur_texte', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Paramètre de paie',
                'verbose_name_plural': 'Paramètres de paie',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ElementPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_element', models.CharField(choices=[('PRIME', 'Prime'), ('RETENUE', 'Retenue'), ('AVANCE', 'Avance'), ('HEURES_SUP', 'Heures supplémentaires'), ('INDEMNITE', 'Indemnité')], max_length=20)),
                ('nom', models.CharField(help_text='Ex: Prime transport, Avance sur salaire...', max_length=100)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_application', models.DateField()),
                ('mois_application', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee_application', models.IntegerField()),
                ('recurrent', models.BooleanField(default=False, help_text='Se répète chaque mois')),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements_paie', to='paie.employe')),
            ],
            options={
                'verbose_name': 'Élément de paie',
                'verbose_name_plural': 'Éléments de paie',
                'ordering': ['-date_application'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_absence', models.CharField(choices=[('CONGE', 'Congé payé'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé maternité'), ('SANS_SOLDE', 'Congé sans solde'), ('RTT', 'Récupération temps de travail'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('nombre_jours', models.IntegerField(help_text='Nombre de jours ouvrables')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20)),
                ('date_approbation', models.DateTimeField(blank=True, null=True)),
                ('motif', models.TextField(blank=True)),
                ('note_rh', models.TextField(blank=True)),
                ('impact_salaire', models.BooleanField(default=False, help_text='Décompte du salaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('approuve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='paie.employe')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('heures_travaillees', models.IntegerField(default=191, help_text='Heures normales du mois')),
                ('heures_supplementaires', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('total_primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_avances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_brut_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_brut_non_imposable', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisation_cnss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisation_amo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cotisation_cimr', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impot_revenu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_calcul', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=False)),
                ('envoye', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('calcule_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='paie.employe')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('employe', 'mois', 'annee')},
            },
        ),
    ]
