# Generated by Django 5.2.4 on 2025-07-22 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='role_systeme',
            field=models.CharField(choices=[('EMPLOYE', 'Employé'), ('RH', 'Ressources Humaines')], default='EMPLOYE', help_text='Rôle dans le système de paie', max_length=20),
        ),
        migrations.AddField(
            model_name='employe',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Compte utilisateur pour l'accès au système", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
