# Generated by Django 5.2.4 on 2025-07-22 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0002_employe_role_systeme_employe_user'),
    ]

    operations = [
    ]
