# Generated by Django 5.2.4 on 2025-07-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0004_add_profil_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('VIEW', 'Consultation'), ('CALCULATE', 'Calcul'), ('ACCESS_DENIED', 'Accès refusé'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=20)),
                ('level', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('CRITICAL', 'Critique')], default='INFO', max_length=10)),
                ('target_model', models.CharField(blank=True, help_text='Modèle concerné (Employe, BulletinPaie, etc.)', max_length=50)),
                ('target_id', models.PositiveIntegerField(blank=True, help_text="ID de l'objet concerné", null=True)),
                ('description', models.TextField(help_text="Description détaillée de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'utilisateur", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="Navigateur/OS de l'utilisateur")),
                ('session_key', models.CharField(blank=True, help_text='Clé de session Django', max_length=40)),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Données supplémentaires en JSON')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text="Utilisateur qui a effectué l'action", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-timestamp'],
            },
        ),
    ]
