# Generated by Django 5.2.4 on 2025-07-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0005_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du site/entreprise', max_length=200)),
                ('code', models.CharField(help_text='Code court (ex: CAS, RAB)', max_length=20, unique=True)),
                ('raison_sociale', models.CharField(max_length=250)),
                ('forme_juridique', models.CharField(default='SARL', max_length=100)),
                ('numero_rc', models.CharField(blank=True, help_text='Numéro registre commerce', max_length=50)),
                ('numero_cnss', models.CharField(blank=True, help_text='Numéro affiliation CNSS', max_length=50)),
                ('numero_patente', models.CharField(blank=True, max_length=50)),
                ('ice', models.CharField(blank=True, help_text='Identifiant Commun Entreprise', max_length=20)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('directeur_general', models.CharField(blank=True, max_length=200)),
                ('directeur_rh', models.CharField(blank=True, max_length=200)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='manager',
            field=models.ForeignKey(blank=True, help_text="Manager direct de l'employé", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='paie.employe'),
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du département', max_length=200)),
                ('code', models.CharField(help_text='Code court (ex: IT, RH, COMPTA)', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('batiment', models.CharField(blank=True, max_length=100)),
                ('etage', models.CharField(blank=True, max_length=50)),
                ('bureau', models.CharField(blank=True, max_length=50)),
                ('code_analytique', models.CharField(blank=True, help_text='Code pour comptabilité analytique', max_length=50)),
                ('budget_annuel', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('departement_parent', models.ForeignKey(blank=True, help_text='Département parent si hiérarchie', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_departements', to='paie.departement')),
                ('responsable', models.ForeignKey(blank=True, help_text='Responsable du département', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departements_geres', to='paie.employe')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='paie.site')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['site', 'nom'],
                'unique_together': {('site', 'code')},
            },
        ),
        migrations.AddField(
            model_name='employe',
            name='departement',
            field=models.ForeignKey(blank=True, help_text="Département d'affectation", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='paie.departement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='site',
            field=models.ForeignKey(blank=True, help_text="Site d'affectation de l'employé", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employes', to='paie.site'),
        ),
    ]
