# Generated by Django 5.2.4 on 2025-07-25 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0006_site_employe_manager_departement_employe_departement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RubriquePersonnalisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code unique (ex: ALLOC, TRANS, MED)', max_length=10, unique=True)),
                ('nom', models.CharField(help_text='Nom complet de la rubrique', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description détaillée')),
                ('type_rubrique', models.CharField(choices=[('GAIN', 'Élément de gain'), ('RETENUE', 'Élément de retenue'), ('COTISATION', 'Cotisation spéciale'), ('EXONERATION', 'Exonération'), ('ALLOCATION', 'Allocation familiale'), ('TRANSPORT', 'Frais de transport'), ('FORMATION', 'Formation professionnelle'), ('MEDICAL', 'Frais médicaux'), ('AUTRE', 'Autre rubrique')], max_length=20)),
                ('mode_calcul', models.CharField(choices=[('FIXE', 'Montant fixe'), ('POURCENTAGE_BRUT', 'Pourcentage du salaire brut'), ('POURCENTAGE_BASE', 'Pourcentage du salaire de base'), ('PAR_ENFANT', 'Montant par enfant'), ('PAR_JOUR', 'Montant par jour travaillé'), ('FORMULE', 'Formule personnalisée')], default='FIXE', max_length=20)),
                ('frequence', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('SEMESTRIEL', 'Semestriel'), ('ANNUEL', 'Annuel'), ('PONCTUEL', 'Ponctuel')], default='MENSUEL', max_length=20)),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe en DH', max_digits=10, null=True)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage à appliquer', max_digits=5, null=True)),
                ('formule_calcul', models.TextField(blank=True, help_text='Formule personnalisée (ex: salaire_base * 0.05 + 100)')),
                ('salaire_minimum', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire minimum pour application', max_digits=10, null=True)),
                ('salaire_maximum', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire maximum pour application', max_digits=10, null=True)),
                ('soumis_ir', models.BooleanField(default=True, help_text="Soumis à l'impôt sur le revenu")),
                ('soumis_cnss', models.BooleanField(default=True, help_text='Soumis aux cotisations CNSS')),
                ('soumis_amo', models.BooleanField(default=True, help_text='Soumis aux cotisations AMO')),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateField(help_text='Date de mise en application')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin (optionnelle)', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, help_text='Utilisateur ayant créé la rubrique', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rubrique Personnalisée',
                'verbose_name_plural': 'Rubriques Personnalisées',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_personnalise', models.DecimalField(blank=True, decimal_places=2, help_text='Montant spécifique pour cet employé (écrase le calcul par défaut)', max_digits=10, null=True)),
                ('pourcentage_personnalise', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage spécifique pour cet employé', max_digits=5, null=True)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, help_text='Note ou justification')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubriques_personnalisees', to='paie.employe')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_concernes', to='paie.rubriquepersonnalisee')),
            ],
            options={
                'verbose_name': 'Rubrique Employé',
                'verbose_name_plural': 'Rubriques Employés',
                'unique_together': {('employe', 'rubrique')},
            },
        ),
    ]
