# Generated by Django 5.2.4 on 2025-07-25 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paie', '0007_rubriquepersonnalisee_employerubrique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerubrique',
            options={'ordering': ['employe__matricule', 'rubrique__ordre_affichage'], 'verbose_name': 'Assignation rubrique employé', 'verbose_name_plural': 'Assignations rubriques employés'},
        ),
        migrations.AlterModelOptions(
            name='rubriquepersonnalisee',
            options={'ordering': ['type_rubrique', 'ordre_affichage', 'nom'], 'verbose_name': 'Rubrique personnalisée', 'verbose_name_plural': 'Rubriques personnalisées'},
        ),
        migrations.RemoveField(
            model_name='employerubrique',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='employerubrique',
            name='note',
        ),
        migrations.RemoveField(
            model_name='rubriquepersonnalisee',
            name='formule_calcul',
        ),
        migrations.RemoveField(
            model_name='rubriquepersonnalisee',
            name='frequence',
        ),
        migrations.RemoveField(
            model_name='rubriquepersonnalisee',
            name='salaire_maximum',
        ),
        migrations.RemoveField(
            model_name='rubriquepersonnalisee',
            name='salaire_minimum',
        ),
        migrations.AddField(
            model_name='employerubrique',
            name='commentaire',
            field=models.TextField(blank=True, help_text='Commentaire ou justification'),
        ),
        migrations.AddField(
            model_name='employerubrique',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='condition_anciennete_min',
            field=models.PositiveIntegerField(default=0, help_text='Ancienneté minimale en mois (0 = pas de condition)'),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='formule_personnalisee',
            field=models.TextField(blank=True, help_text='Formule Python (ex: salaire_base * 0.05 if anciennete > 5 else 0)'),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='montant_par_enfant',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant par enfant (si mode = PAR_ENFANT)', max_digits=10),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='ordre_affichage',
            field=models.PositiveIntegerField(default=100, help_text="Ordre d'affichage sur le bulletin (plus petit = en haut)"),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='periodicite',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel'), ('PONCTUEL', 'Ponctuel')], default='MENSUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='plafond_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Plafond mensuel (optionnel)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rubriquepersonnalisee',
            name='plancher_mensuel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant minimum (optionnel)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerubrique',
            name='date_debut',
            field=models.DateField(help_text='Date de début pour cet employé'),
        ),
        migrations.AlterField(
            model_name='employerubrique',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Date de fin pour cet employé (optionnel)', null=True),
        ),
        migrations.AlterField(
            model_name='employerubrique',
            name='montant_personnalise',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant spécifique pour cet employé (surcharge la règle générale)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employerubrique',
            name='rubrique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_assignes', to='paie.rubriquepersonnalisee'),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='code',
            field=models.CharField(help_text='Code unique (ex: TRANSP, MUTU, ANCIENNET)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='date_debut',
            field=models.DateField(help_text="Date de début d'application"),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='date_fin',
            field=models.DateField(blank=True, help_text="Date de fin d'application (optionnel)", null=True),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='mode_calcul',
            field=models.CharField(choices=[('FIXE', 'Montant fixe'), ('POURCENTAGE', 'Pourcentage du salaire'), ('PAR_ENFANT', 'Par enfant'), ('FORMULE', 'Formule personnalisée')], help_text='Comment calculer le montant', max_length=20),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='montant_fixe',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant fixe en DH (si mode = FIXE)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='nom',
            field=models.CharField(help_text='Nom affiché sur le bulletin (ex: Prime Transport)', max_length=100),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='pourcentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage du salaire (si mode = POURCENTAGE)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='soumis_amo',
            field=models.BooleanField(default=True, help_text="Soumis à l'AMO"),
        ),
        migrations.AlterField(
            model_name='rubriquepersonnalisee',
            name='type_rubrique',
            field=models.CharField(choices=[('GAIN', 'Gain/Prime'), ('RETENUE', 'Retenue'), ('ALLOCATION', 'Allocation'), ('COTISATION', 'Cotisation spéciale')], help_text='Type de rubrique', max_length=20),
        ),
    ]
